using UnityEngine;
using UnityEngine.InputSystem;
using PQ.Generated;


namespace PQ
{
    /*
    Input receiver that maps gameplay control input to the game event system.

    Assumes that an autogenerated c# class is provided that maps to in-editor-configured
    player input/control settings.
    */
    [System.Serializable]
    [AddComponentMenu("PlayerGameplayInputReceiver")]
    public class PlayerGameplayInputReceiver : MonoBehaviour
    {
        private PlayerControls _generatedPlayerControls;

        private InputAction _moveHorizontal;
        private InputAction _jumpUp;
        private InputAction _standUp;
        private InputAction _lieDown;
        private InputAction _use;
        private InputAction _fire;

        void Awake()
        {
            PlayerControls controls = new PlayerControls();

            _generatedPlayerControls = controls;
            _moveHorizontal = controls.Gameplay.MoveHorizontal;
            _jumpUp         = controls.Gameplay.JumpUp;
            _standUp        = controls.Gameplay.StandUp;
            _lieDown        = controls.Gameplay.LieDown;
            _use            = controls.Gameplay.Fire;
            _fire           = controls.Gameplay.Use;
        }


        void OnEnable()
        {
            _generatedPlayerControls.Gameplay.Enable();
            _moveHorizontal.started   += OnMoveHorizontalStarted;
            _moveHorizontal.canceled  += OnMoveHorizontalStopped;
            _jumpUp        .performed += OnJumpUp;
            _standUp       .performed += OnStandUp;
            _lieDown       .performed += OnLieDown;
            _use           .performed += OnUse;
            _fire          .performed += OnFire;
        }

        void OnDisable()
        {
            _generatedPlayerControls.Gameplay.Disable();
            _moveHorizontal.started   -= OnMoveHorizontalStarted;
            _moveHorizontal.canceled  -= OnMoveHorizontalStopped;
            _jumpUp        .performed -= OnJumpUp;
            _standUp       .performed -= OnStandUp;
            _lieDown       .performed -= OnLieDown;
            _use           .performed -= OnUse;
            _fire          .performed -= OnFire;
        }

        private void OnMoveHorizontalStarted(InputAction.CallbackContext context)
        {
            int direction = context.action.ReadValue<float>() < 0.00f ? -1 : 1;
            GameEventCenter.startHorizontalMoveCommand.Trigger(direction);
        }

        private void OnMoveHorizontalStopped(InputAction.CallbackContext _)
        {
            GameEventCenter.stopHorizontalMoveCommand.Trigger("Received input to stop horizontal movement");
        }

        private void OnJumpUp(InputAction.CallbackContext _)
        {
            GameEventCenter.jumpCommand.Trigger("Received jump up input");
        }

        private void OnStandUp(InputAction.CallbackContext _)
        {
            GameEventCenter.standUpCommand.Trigger("Received stand up input");
        }

        private void OnLieDown(InputAction.CallbackContext _)
        {
            GameEventCenter.lieDownCommand.Trigger("Received lie down input");
        }

        private void OnUse(InputAction.CallbackContext _)
        {
            GameEventCenter.useCommand.Trigger("Received use input");
        }

        private void OnFire(InputAction.CallbackContext _)
        {
            GameEventCenter.fireCommand.Trigger("Received fire input");
        }
    }
}
